Desktop, mobile version and dynamic HTML with JavaScript
MuhammadUsmanAslam/programmer-summit pull request #1
Opened 2023-02-08 16:57 UTC by MuhammadUsmanAslam

- Mobile version designed with HTML and CSS
- Desktop version designed using media query
- Speakers section created using dynamic HTML and JavaScript

Here is the Introduction Video: https://www.loom.com/share/d93d875569584cbca7908b67e152cb02
Here is the Live Link: https://muhammadusmanaslam.github.io/programmer-summit/index.html

2023-02-08 17:39 UTC, omarsalem7 requested changes
Hi @MuhammadUsmanAslam 😊, 

Good job so far! 👏
You have done well reaching this point of the milestone, but there are some issues that you still need to work on to go to the next project but you are almost there! 

![you-are-near](https://media.giphy.com/media/j7vckgz15cAYmxatzB/giphy.gif)

## Highlights
- There is no linter error present ✔️
- The Pull Request has a proper title and description. ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-08 17:39 UTC, omarsalem7 commented on README.md
>  If you like this project...
- [ ] Kindly consider giving appropriate credit to [Cindy Shin](https://www.behance.net/adagio07) the [author of the original design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015), as required by the [Creative Commons License](https://creativecommons.org/licenses/).

2023-02-08 17:39 UTC, omarsalem7 commented on index.html
> +        </ul>
- [ ] Kindly consider matching your design with Behance design by reducing the size of the image and font to match it

| Your design  | Behance design|
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/53402600/217606796-01b90298-6704-4dbe-bd9c-efb4f852953b.png)  | ![image](https://user-images.githubusercontent.com/53402600/217606865-c28e46ff-07c7-4b67-87a8-d54d4c18e4bd.png) |

2023-02-08 17:39 UTC, omarsalem7 commented on about.html
> +    <hr class="hr-full">
- [ ] Kindly consider matching your design with Behance by choosing the correct font, padding, and margin

| Your design  | Behance design|
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/53402600/217607996-78fad2d2-6494-4fa6-9b2e-e9ad75197623.png)  | ![image](https://user-images.githubusercontent.com/53402600/217608128-74937e30-4dfa-4ff0-9825-2ebc3a6d1b92.png) |

2023-02-09 08:58 UTC, PinkMoon25 approved these changes
Hi @MuhammadUsmanAslam , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media4.giphy.com/media/lD76yTC5zxZPG/giphy.gif"/>

## Highlights
Linters :heavy_check_mark: 
Github flow :heavy_check_mark: 
Good PR & Commit :heavy_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-09 12:22 UTC, merged